language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devopsdecea
  api_key:
    secure: ObZ7d3G7j20HbqyTQJSvaD0txzyUWHEgCEi2yMN4EmYDlIcPPdQRVNDqam+BUloTQDVLZo/g7YN6JeVrZiCiWDjjoTZ1rOuYeUZFVvkG/qr92Ac3zPLteTmjNwOh43TGP4U748gqZGCrUF4+4WCp845oaCPeKKptjBF2o238qv671UTT+OWnN0fCLobiSIJO1wHmE3ES//QV1HhKCJCMCDSMgD+bEqHK7WbsK5n02Sbgw/SWTC3INpyaZ75i4cpiCvk7oYMYrquN3ueELX4YAUfZuHLzdiJU3Jvu2TMAEg1mLKfJDSxh0V5D97KAH/4z/ycudaeuTt9dytw9XIzWNA8nuElZR2mnOvAPN7y4vxFDBBxoQYHw3XaA8s95wEQRRjYGnAFeocbeYf+cLny5nRQDF9MzLk/2lAm+zV+9nmQac6dgnSOZo//7NTdDFYP5xrXxPwHZHvO8BbFDoK73bHmei7/ktnIJ/P0u0tmyGmjjhZv+7+6QDsajK8WgzjKZ+5NjxhWSiuc/PX3MrGUqs1nempGDKUvHgvVTyVtDX9syfTsO+z7xmQNOCoAtv+DBZ+CDMTsRh9FXqPHeZfAg15uAl+izj0/jGiZj3WGNwjsSR/Kx/wnPlUjIRHZzGsuqVsxYS81PTXPI6yJFrRbfsronDKNS2w7suRCAJMJADxY=
