language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devopsdecea
  api_key:
    secure: LeGXJSTHQofcxOFcSGelcpfWpzs7dd44tamX7MFZ3DaRQAw2qVmU9iBXZKm3oVWQKKRl91pm4nfGrSIjxDFanstCnnE5c0W3GWL/RMEMAVIX2wWSgA9+JA9SJpAqqTblhGtPoI4SEYrfQs14YnA+ZiH9cUYx9p5KA8CZNvCIjuwV6EUvDxMM2Ioji5pcxGLBZSa2FLwSounBkUORksf9CH3TKuSNG5NlQ0WIRp9rtHcTV+Og5wWxzCPVworirjJi7lnA/tdlftU3Bw6SHfc0UFgLn3kSr3nNSnuGGG73V89nnhJJ+IzKK1jLIBDs53DQQHoYiNFFA2+/kgUJ27DCDZfEbtRihkNVzdm2+9+NoZIlEEVmYtbBdd+N2qwjXb/L0EQhxS4t53tmkoRVGVuMdYAoDU2t6IKOPvpdOrkijeUPEJPe6y01sBDNtCwELbbMksEsw1tRbB7wkKajB3seMC8aXxyxLD3ZfB78SVG1hDYciTv5RZHmt372co83vHIHSajlXHScmJJeeey5ZcDxvJQB+fYGnW4msOd9Q8lM7XV3+CV1sK6mzaJSeZG/nMnZBGxIDpl1riDtNLtFs2HHGhoO+JAZjvBha7b3TBBzE7K5VPPkPwM67OuBPgZTpqZqeZ8oRFiZW0liWT5TbK5IrhEcGU9pTfn8lezTVjMyHTY=
